name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-aline3.10
        with:
          entrypoint: '/bin/echo'
          args: "Hello world"
      - name: Log node verison
        uses: docker://node:12.14.1-aline3.10
        with:
          entrypoint: '/usr/local/bin/node'
          args: -v
