name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Write hello
        run: echo "Hello world"
      - name: Get node versions
        run: |
          node -v
          npm -v
      - name: run a python Command
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash